# Generated by Django 3.2.6 on 2021-10-14 06:01

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nom', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('tattoo_id', models.AutoField(primary_key=True, serialize=False)),
                ('tattoo_nom', models.CharField(max_length=100)),
                ('tattoo_img', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('categoria_id', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.RESTRICT, related_name='Tattoos', to='api.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
